"use client";

import { icons } from "@sanity/icons";
import {
  Badge,
  Box,
  Card,
  Code,
  Container,
  Flex,
  Grid,
  Heading,
  Stack,
  Tab,
  TabList,
  Text,
  TextInput,
} from "@sanity/ui";
import { useMemo, useState } from "react";
import type { Tool } from "sanity";

import index from "@/design/tokens.index.json";

/*
  "Design tokens" — the Studio's read-only view of the design system,
  laid out like Figma's Variables panel: token rows, one column per
  mode, resolved values with swatches. Plain @sanity/ui, themed by
  the Studio.

  Two tabs:
    · Site tokens   — what the code actually consumes (globals.css)
    · Figma library — the raw variable collection, every mode

  The data is generated by `npm run tokens` (scripts/build-token-
  index.mjs) into src/design/tokens.index.json, which also records
  when each source was last re-exported.
*/

type Row = {
  path: string;
  name: string;
  type: string;
  values?: Record<string, string>;
  value?: string;
  aliasOf?: Record<string, string>;
  utility?: string | null;
  detail?: { lineHeight?: string; letterSpacing?: string };
};

const isColor = (v?: string) => !!v && /^(#|rgb|hsl|color\()/i.test(v.trim());

function relativeTime(iso?: string | null) {
  if (!iso) return "unknown";
  const then = new Date(iso).getTime();
  if (Number.isNaN(then)) return "unknown";
  const days = Math.floor((Date.now() - then) / 86_400_000);
  const date = new Date(iso).toLocaleDateString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
  if (days <= 0) return `${date} (today)`;
  if (days === 1) return `${date} (yesterday)`;
  return `${date} (${days} days ago)`;
}

function Swatch({ value }: { value: string }) {
  return (
    <span
      aria-hidden
      style={{
        display: "inline-block",
        width: 12,
        height: 12,
        borderRadius: 3,
        marginRight: 6,
        verticalAlign: "-2px",
        boxShadow: "inset 0 0 0 1px rgba(127,127,127,.35)",
        /* alpha tokens read correctly over a checker */
        backgroundImage: `linear-gradient(${value}, ${value}), repeating-conic-gradient(#bbb 0% 25%, #fff 0% 50%)`,
        backgroundSize: "auto, 8px 8px",
      }}
    />
  );
}

/* one token = one row; a cell per mode */
function TokenRow({ row, modes }: { row: Row; modes: string[] }) {
  const single = row.value !== undefined;
  return (
    <Flex gap={3} paddingY={2} style={{ borderTop: "1px solid var(--card-border-color)" }}>
      <Box style={{ width: 220, flex: "none", minWidth: 0 }}>
        <Stack space={2}>
          <Code size={1}>{row.name}</Code>
          {row.utility && (
            <Text size={0} muted textOverflow="ellipsis">
              {row.utility}
            </Text>
          )}
        </Stack>
      </Box>

      {single ? (
        <Box flex={1}>
          <Stack space={2}>
            <Code size={1}>{row.value}</Code>
            {(row.detail?.lineHeight || row.detail?.letterSpacing) && (
              <Text size={0} muted>
                {row.detail?.lineHeight && `line-height ${row.detail.lineHeight}`}
                {row.detail?.lineHeight && row.detail?.letterSpacing && "  ·  "}
                {row.detail?.letterSpacing && `tracking ${row.detail.letterSpacing}`}
              </Text>
            )}
          </Stack>
        </Box>
      ) : (
        modes.map((mode) => {
          const v = row.values?.[mode];
          const alias = row.aliasOf?.[mode];
          return (
            <Box key={mode} flex={1} style={{ minWidth: 0 }}>
              {v ? (
                <Stack space={2}>
                  <Text size={1} style={{ whiteSpace: "nowrap" }} textOverflow="ellipsis">
                    {isColor(v) && <Swatch value={v} />}
                    <Code size={1}>{v}</Code>
                  </Text>
                  {alias && (
                    <Text size={0} muted title={alias} textOverflow="ellipsis">
                      → {alias.split("/").pop()}
                    </Text>
                  )}
                </Stack>
              ) : (
                <Text size={1} muted>
                  —
                </Text>
              )}
            </Box>
          );
        })
      )}
    </Flex>
  );
}

function Group({
  title,
  subtitle,
  rows,
  modes,
}: {
  title: string;
  subtitle?: string;
  rows: Row[];
  modes: string[];
}) {
  if (!rows.length) return null;
  return (
    <Card padding={4} radius={3} border>
      <Stack space={3}>
        <Flex gap={2} align="baseline" wrap="wrap">
          <Text size={1} weight="medium">
            {title}
          </Text>
          {subtitle && (
            <Text size={0} muted>
              {subtitle}
            </Text>
          )}
          <Badge>{rows.length}</Badge>
        </Flex>
        {rows[0]?.value === undefined && (
          <Flex gap={3}>
            <Box style={{ width: 220, flex: "none" }}>
              <Text size={0} muted>
                TOKEN
              </Text>
            </Box>
            {modes.map((m) => (
              <Box key={m} flex={1}>
                <Text size={0} muted>
                  {m.toUpperCase()}
                </Text>
              </Box>
            ))}
          </Flex>
        )}
        <Stack>
          {rows.map((row) => (
            <TokenRow key={row.path} row={row} modes={modes} />
          ))}
        </Stack>
      </Stack>
    </Card>
  );
}

export default function DesignTokensPanel() {
  const [query, setQuery] = useState("");
  const [tab, setTab] = useState<"site" | "figma">("site");

  const q = query.trim().toLowerCase();
  const match = (rows: Row[]) =>
    !q
      ? rows
      : rows.filter(
          (r) =>
            r.path.toLowerCase().includes(q) ||
            (r.utility ?? "").toLowerCase().includes(q) ||
            Object.values(r.values ?? {}).some((v) =>
              String(v).toLowerCase().includes(q),
            ) ||
            String(r.value ?? "").toLowerCase().includes(q),
        );

  /* the Figma collection, grouped the way the variables panel groups it */
  const figmaGroups = useMemo(() => {
    const by = new Map<string, Row[]>();
    for (const t of index.figma.tokens as Row[]) {
      const group = t.path.split("/").slice(0, -1).join(" / ");
      if (!by.has(group)) by.set(group, []);
      by.get(group)!.push(t);
    }
    return [...by.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  }, []);

  const siteModes = index.css.modes as string[];
  const figmaModes = index.figma.modes as string[];

  return (
    <Card height="fill" overflow="auto">
      <Container width={5} paddingX={4} paddingY={5}>
        <Stack space={5}>
          <Flex align="flex-end" justify="space-between" gap={4} wrap="wrap">
            <Stack space={3}>
              <Heading as="h1" size={3}>
                Design tokens
              </Heading>
              <Text size={1} muted>
                Every value the site is allowed to build from — read-only: edit in
                Figma, re-export, run <Code size={1}>npm run tokens</Code> · Figma
                exported {relativeTime(index.sources.figma.updatedAt)} · site tokens
                changed {relativeTime(index.sources.css.updatedAt)}
              </Text>
            </Stack>
            <Badge tone={figmaModes.length < 6 ? "caution" : "positive"} fontSize={1} padding={3}>
              {figmaModes.length} / 6 modes exported
            </Badge>
          </Flex>

          <Flex gap={3} align="center" wrap="wrap">
            <TabList space={1}>
              <Tab
                id="site-tab"
                aria-controls="site-panel"
                label="Site tokens"
                selected={tab === "site"}
                onClick={() => setTab("site")}
              />
              <Tab
                id="figma-tab"
                aria-controls="figma-panel"
                label="Figma library"
                selected={tab === "figma"}
                onClick={() => setTab("figma")}
              />
            </TabList>
            <Box flex={1} style={{ minWidth: 240 }}>
              <TextInput
                placeholder="Filter tokens, values, or utilities…"
                value={query}
                onChange={(e) => setQuery(e.currentTarget.value)}
              />
            </Box>
          </Flex>

          <Stack space={3}>
            {tab === "site" ? (
              <>
                <Group
                  title="Color — semantic"
                  subtitle="flips per data-mode wrapper; never hardcode a mode color"
                  rows={match(index.css.semantic as Row[])}
                  modes={siteModes}
                />
                <Group
                  title="Spacing"
                  subtitle="the Figma spacing scale"
                  rows={match(index.css.spacing as Row[])}
                  modes={siteModes}
                />
                <Group
                  title="Typography"
                  subtitle="fluid between the 428px and 1440px frames"
                  rows={match(index.css.type as Row[])}
                  modes={siteModes}
                />
                <Group title="Radius" rows={match(index.css.radius as Row[])} modes={siteModes} />
                <Group title="Fonts" rows={match(index.css.fonts as Row[])} modes={siteModes} />
              </>
            ) : (
              figmaGroups.map(([group, rows]) => (
                <Group key={group} title={group} rows={match(rows)} modes={figmaModes} />
              ))
            )}
          </Stack>
        </Stack>
      </Container>
    </Card>
  );
}
