import { buildTheme } from "@sanity/themer";

/*
  Studio theme: monochrome, generated by the official @sanity/themer
  (2026-08-04) instead of a hand-rolled remap. A neutral gray accent
  replaces Sanity's blue scale (primary buttons, focus rings, links),
  and contrast 100 strips every tint from the text/border scale — no
  colored border lines in either appearance mode. Semantic colors
  (critical red, positive green, caution yellow) are untouched.

  The themer sidebar (themerTool in sanity.config.ts, top-right of
  the Studio) previews palette changes live; it starts from these
  same options — if you land on something better, copy its snippet
  here.
*/

export const themeOptions = {
  accent: "#808080",
  contrast: 100,
} as const;

export const theme = buildTheme(themeOptions);
